#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_SUNWAVECORP_FINGERPRINT) += sunwavecorp/
obj-$(CONFIG_ET310_FINGERPRINT) += et310/
obj-$(CONFIG_FPC_REE_FINGERPRINT) += fpc_ree/
obj-$(CONFIG_GF3258_FINGERPRINT) += gf3258/
